source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'OriginateRemoteCollection-Example', :exclusive => true do
  pod "OriginateRemoteCollection", :path => "../"
  pod "DZNEmptyDataSet"
end


