source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'OriginateAsyncCollection-Example', :exclusive => true do
  pod "OriginateAsyncCollection", :path => "../"
  pod "DZNEmptyDataSet"
end


